### ISSUE TITLE
Uploading video results in stream error

### ISSUE THREAD

**Issue by bc3tech** [facebook-csharp-sdk/facebook-csharp-sdk#181]
I'm trying to upload videos to Facebook using the methods in place as follows:

```
        dynamic parameters = new ExpandoObject();
        parameters.source = new fb.FacebookMediaObject { ContentType = mimeType, FileName = request.Filename }
            .SetValue(ServiceCommon.Common.GetBytesFromStream(videoData).ToArray());
        parameters.title = request.Title;
        parameters.description = request.Description;
```

but when I do large videos (>~20mb), I get the following error consistently:
Facebook upload failed: mimetype [video/mp4]System.Net.WebException: The request was aborted: The request was canceled. ---> System.IO.IOException: Cannot close stream until all bytes are written.
   at System.Net.ConnectStream.CloseInternal(Boolean internalCall, Boolean aborting)
   --- End of inner exception stack trace ---
   at System.Net.ConnectStream.CloseInternal(Boolean internalCall, Boolean aborting)
   at System.Net.ConnectStream.System.Net.ICloseEx.CloseEx(CloseExState closeState)
   at System.Net.ConnectStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.Stream.Dispose()
   at Facebook.FacebookClient.Api(HttpMethod httpMethod, String path, Object parameters, Type resultType)
   at Facebook.FacebookClient.Post(String path, Object parameters)
   at CallSite.Target(Closure , CallSite , FacebookClient , String , Object )
   at FacebookTransferService.Upload(FacebookUploadRequest request, Stream videoData)

**Comment by HanaaGhasoub** [comment]
Dear bc3tech,
i faced the same problem and try to follow your solution but nothing new added,so if could you share with me full code which make a post video to facebook.
thanks a lot in advance.
